services:
  nginx:
    build: ./docker/nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./projects:/var/www
      - ./docker/nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - php73
      - php74
      - php80
      - php81
      - php83

  php73:
    build: ./docker/php/7.3
    container_name: php73

  php74:
    build: ./docker/php/7.4
    container_name: php74

  php80:
    build: ./docker/php/8.0
    container_name: php80

  php81:
    build: ./docker/php/8.1
    container_name: php81

  php83:
    build: ./docker/php/8.3
    container_name: php83

  workspace:
    build: ./docker/workspace
    container_name: workspace
    working_dir: /var/www
    volumes:
      - ./projects:/var/www
    command: ["/bin/bash", "-c", "cron -f"]

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    volumes:
      - mysql-data:/var/lib/mysql

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"

  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=mysql
      - PMA_USER=root
      - PMA_PASSWORD=123456
    depends_on:
      - mysql

volumes:
  mysql-data:
